export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const UPDATE_ROOT = "UPDATE_ROOT";
export const TOGGLE_FLATS = "TOGGLE_FLATS";
export const UPDATE_QUALITY = "UPDATE_QUALITY";
export const UPDATE_SEVENTH = "UPDATE_SEVENTH";
export const UPDATE_EXTENSION = "UPDATE_EXTENSION";
export const UPDATE_CHORD_NAME = "UPDATE_CHORD_NAME";
export const UPDATE_SCALE_NAME = "UPDATE_SCALE_NAME";
export const DISCARD_CHORD = "DISCARD_CHORD";

export const UPDATE_NAMING_CONVENTION = "UPDATE_NAMING_CONVENTION";
export const TOGGLE_HANDS = "TOGGLE_HANDS";
export const TOGGLE_NOTES_INTERVALS = "TOGGLE_NOTES_INTERVALS";
export const TUNE_UP_STRING = "TUNE_UP_STRING";
export const TUNE_DOWN_STRING = "TUNE_DOWN_STRING";
export const TUNE_UP_ALL = "TUNE_UP_ALL";
export const TUNE_DOWN_ALL = "TUNE_DOWN_ALL";
export const SET_TUNING_PRESET = "SET_TUNING_PRESET";
export const CHECK_LOCAL_SETTINGS = "CHECK_LOCAL_SETTINGS";
